<p style="text-align:center"> 
    <a href="https://www.linkedin.com/in/flavio-aguirre-12784a252/" target="_blank"> 
    <img src="../assets/logo.png" width="200" alt="Flavio Aguirre Logo"> 
    </a>
</p>

<h1 align="center"><font size="7"><strong>📉 ByeBye Predictor</strong></font></h1>
<br>
<hr>

## Data Acquisition

**Date**: September 3, 2025
<br>
**Subject**: Start, completion, and summary of the data acquisition and validation module.

In this notebook, we lay the groundwork for our machine learning project by acquiring and validating the datasets that will be used in the modeling process. The data acquisition process is designed to ensure reproducibility and extensibility, leveraging structured and unstructured data sources.

As indicated in the project description, data collection was structured into two complementary approaches.
On the one hand, a tabular dataset obtained from the reliable source [Kaggle - Telco Customer Churn](https://www.kaggle.com/datasets/blastchar/telco-customer-churn) was used. This labeled dataset provides a solid foundation for initial model training, allowing feature engineering techniques to be applied to the structured data to optimize its performance.

On the other hand, a second source of unstructured data will be incorporated, consisting of real user comments extracted from [Reddit](https://www.reddit.com/r/argentina/comments/1i924b2/movistar_av%C3%ADspense/) to simulate a real-life environment for a dataset that does have comments, using the platform's official API. This layer of textual data will allow the model to be enriched through sentiment analysis, capturing nuances and customer perceptions that are not always reflected in traditional tabular data.



#### Expected final result of Notebook 01

Successful loading of the structured and unstructured datasets using functions from the src.data_loader module.

Quick integrity check of both datasets.

Documented metadata (size, structure, observations).
<br>
<br>
<br>


----

<br>

### We import the necessary libraries

In [1]:
from notebooks_setup import PROJECT_ROOT
from src.data_loader import (
    DataLoaderConfig, loader_telco_data, loader_reddit_comments, preview_df
    )

2025-09-03 10:54:05,910 | src.utils | INFO | Added project root to sys.path: C:\Users\Pc\Desktop\github

When you run the following cell, the datasets will be downloaded to the data/raw/ folder located in the project's root directory. Along with them, their respective ``metadata_{dataset_name}.md`` documentation will be generated, which defines the metadata for each dataset.

In [2]:
!python -m src.data_loader >nul 2>&1
print("'data_loader' module ran successfully.")

'data_loader' module ran successfully.

In [3]:
# Load the datasets
df_telco = loader_telco_data()
reddit_comments = loader_reddit_comments()

2025-09-03 10:54:26,046 | src.data_loader | WARNING | Telco dataset not found locally. Downloading from Kaggle or fallback URL...
2025-09-03 10:54:26,177 | src.data_loader | ERROR | Kaggle API failed: Could not find kaggle.json. Make sure it's located in C:\Users\Pc\.kaggle. Or use the environment method. See setup instructions at https://github.com/Kaggle/kaggle-api/. Trying fallback URL...
2025-09-03 10:54:26,515 | src.data_loader | INFO | Loaded CSV from: https://raw.githubusercontent.com/IBM/telco-customer-churn-on-icp4d/master/data/Telco-Customer-Churn.csv | Shape: (7043, 21)
2025-09-03 10:54:26,516 | src.data_loader | INFO | Completed: load_csv_from_url
2025-09-03 10:54:26,570 | src.data_loader | INFO | Loaded CSV: C:\Users\Pc\Desktop\github\byebye_predictor\data\raw\telco_customer_churn.csv | Shape: (7043, 21)
2025-09-03 10:54:26,571 | src.data_loader | INFO | Completed: load_csv
2025-09-03 10:54:26,572 | src.data_loader | INFO | Telco data loaded successfully with shape (7043, 21)
2025-09-03 10:54:26,575 | src.data_loader | INFO | Loaded CSV: C:\Users\Pc\Desktop\github\byebye_predictor\data\raw\public_comments.csv | Shape: (44, 7)
2025-09-03 10:54:26,576 | src.data_loader | INFO | Completed: load_csv
2025-09-03 10:54:26,577 | src.data_loader | INFO | Reddit comments data loaded successfully with shape (44, 7)

We verify the correct loading of the data.

In [4]:
print("\nDataframe 'Telco Customer Churn' loaded successfully")
print(f"Data shape: {df_telco.shape}")
print(f"Data preview:")
preview_df(df_telco,10)

Dataframe 'Telco Customer Churn' loaded successfully
Data shape: (7043, 21)
Data preview:

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
5,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,Yes
6,1452-KIOVK,Male,0,No,Yes,22,Yes,Yes,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Credit card (automatic),89.10,1949.4,No
7,6713-OKOMC,Female,0,No,No,10,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,No,Mailed check,29.75,301.9,No
8,7892-POOKP,Female,0,Yes,No,28,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes
9,6388-TABGU,Male,0,No,Yes,62,Yes,No,DSL,Yes,...,No,No,No,No,One year,No,Bank transfer (automatic),56.15,3487.95,No

#### We observe the information in this pandas dataframe

In [5]:
print("Information about the dataset:")
df_telco.info()

Information about the dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

<br>

#### Real Reddit Customer Comments

We verify the integrity of the dataset that will provide us with the fictitious comments to later integrate them with the structured data ``telco_customer_churn``.

In [6]:
print(f"Data shape: {reddit_comments.shape}")
preview_df(reddit_comments, 10)

Data shape: (44, 7)

,comment_id,body,author,created_utc,score,parent_id,is_submitter
0,m8yc3ia,"No es que son 5000, son 5000 por cada persona ...",International_Luck60,1.737743e+09,116,t3_1i924b2,False
1,m8yjtrr,"Lo hacen de toda la vida. Antes eran los ""SMS ...",Happy_Scrotum,1.737745e+09,49,t3_1i924b2,False
2,m8zffac,por eso mismo me fui de personal en su momento...,usergghs,1.737754e+09,18,t3_1i924b2,False
3,m901q6d,"Telefono pre pago, desde el Nokia 1100 hasta d...",Belkan2087,1.737761e+09,9,t3_1i924b2,False
4,m90pvr2,36 LUCAS POR 6GB!!!! KJJJ \nLiteralmente por e...,Storpa2,1.737769e+09,8,t3_1i924b2,False
5,m8ypdp1,5mil pesos?\n\nCon 5mil pesos me compro harto ...,CordobezEverdeen,1.737747e+09,7,t3_1i924b2,False
6,m8yejn0,Cómo llego a esa pantalla en la app?,pachirul0,1.737744e+09,6,t3_1i924b2,False
7,m8z8iwz,"Aguante el prepago, le cargas cuando querés.yo...",Badracha,1.737752e+09,7,t3_1i924b2,False
8,m917jb1,Esta semana me cambié a Tuenti por estas cuest...,Shoddy_Scientist6369,1.737775e+09,5,t3_1i924b2,False
9,m915oyr,Lo pagas un poco mas barato que yo!\n\nYo teng...,Fran_1989,1.737775e+09,2,t3_1i924b2,False

In [7]:
print("Information about the dataset:")
reddit_comments.info()

Information about the dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   comment_id    44 non-null     object
 1   body          44 non-null     object
 2   author        42 non-null     object
 3   created_utc   44 non-null     float64
 4   score         44 non-null     int64
 5   parent_id     44 non-null     object
 6   is_submitter  44 non-null     bool
dtypes: bool(1), float64(1), int64(1), object(4)
memory usage: 2.2+ KB

#### Creating a Checkpoint (Data Snapshot)

To ensure the integrity and consistency of the project, we will establish a formal checkpoint before proceeding with exploratory analysis.

``Technical Rationale``: The purpose of this step is to "freeze" the state of the data at a specific point in time. This action is critical to mitigate the risks associated with the volatility of the original sources. By creating an immutable version, we decouple ourselves from possible future changes to the Kaggle datasets or the results from the Reddit API.

Impact on the Pipeline: This practice ensures full reproducibility of subsequent analyses. Both the Exploratory Data Analysis (EDA) phase and subsequent model training will be run on this same version of the data. This eliminates the possibility of inconsistencies and allows for rigorous and reliable validation of the results obtained at each stage of the project.

In [8]:
config = DataLoaderConfig(out_dir=PROJECT_ROOT / "data" / "interim")

In [9]:
path_telco= f"{config.out_dir}/telco_customer_churn_snapshot_2025-09-03.csv"
path_public_comments = f"{config.out_dir}/public_comments_snapshot_2025-09-03.csv"

In [10]:
for df, path in zip([df_telco, reddit_comments], [path_telco, path_public_comments]):
    df.to_csv(path, index=False)
print(f"Datasets saved to {config.out_dir}")

Datasets saved to C:\Users\Pc\Desktop\github\byebye_predictor\data\interim

### Conclusion and Next Steps

We have successfully completed the data acquisition phase. We have two robust and validated datasets that provide us with a 360° view of the problem: a quantitative baseline of customer behavior and a qualitative layer of perception.

The entire process has been documented and versioned in our repository, ensuring reproducibility. We are now ready to move on to the next stage of the pipeline:

-- >  ``Exploratory Data Analysis (EDA)``.

* Data Preprocessing and Cleaning.

* Feature Engineering on the tabular dataset.

* Natural Language Processing (NLP) and Sentiment Analysis on the Reddit dataset.

<br>

<br>

<hr>

## Author

<a href="https://www.linkedin.com/in/flavio-aguirre-12784a252/">**Flavio Aguirre**</a>
<br>
<a href="https://coursera.org/share/e27ae5af81b56f99a2aa85289b7cdd04">***Data Scientist***</a>